name: "Test"
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ["12"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: "Install dependencies"
      run: npm install
    - name: "Run tests"
      run: npm test
